@startuml
' http://plantuml.com/
' https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml


'title ユースケース図

left to right direction
skinparam packageStyle rectangle

actor ゲスト
' 教員
actor 登録ユーザ
' 図書館員,モデレータ
actor リポジトリ管理者
actor システム管理者
' 外部システム
actor IRDB 
actor ERDB_JP
actor RSS_Reader

' WEKO3
actor コミュニティ管理者

rectangle WEKO3 {

' ゲスト
ゲスト -- (キーワード検索する)
ゲスト -- (インデックスツリーからディレクトリ検索する)
ゲスト -- (アイテムの詳細画面を閲覧する)
ゲスト -- (ランキングを閲覧する)

' 登録ユーザ
登録ユーザ -- (アイテムを登録する)

' リポジトリ管理者
リポジトリ管理者 -- (アイテムタイプを作成する)
リポジトリ管理者 -- (アイテムタイプを編集する)
リポジトリ管理者 -- (アイテムを一括管理する)
リポジトリ管理者 -- (インデックスツリーを編集する)
リポジトリ管理者 -- (アイテムを査読／承認する)
リポジトリ管理者 -- (インポートする)
リポジトリ管理者 -- (ログ解析結果を閲覧する)
リポジトリ管理者 -- (デザインをカスタマイズする)
リポジトリ管理者 -- (ランキングを管理する)
リポジトリ管理者 -- (OAI-PMHを管理する)

' システム管理者
システム管理者  -- (ユーザを管理する)

' 外部システム連携
(OAI-PMH経由メタデータを提供する) -- IRDB
(KBART経由で雑誌情報を提供する) -- ERDB_JP
(RSS経由でアイテム情報を提供する) --  RSS_Reader

}
@enduml