@startuml

header Architecture
footer 1 of 1
title 即時OA関連システムのアーキテクチャ図

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/refs/heads/main/icons/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/postgresql.puml
!include DEVICONS2/elasticsearch.puml


AddElementTag("target", $fontColor="#ffffbf", $borderColor="#ffffbf",$bgColor="#444444")
AddElementTag("constructing", $fontColor="#000000",$borderColor="#000000",,$bgColor="#ffffff",$borderStyle=DashedLine())
AddRelTag("dotted", $lineStyle = DottedLine())
AddRelTag("dashed", $lineStyle = DashedLine())

Person(userLib, "図書館員", "機関リポジトリを運用", $sprite="users")
Person(userRes, "研究者", "", $sprite="users")
Person(userIT, "ITスタッフ", "基盤センター職員等、\n機関の情報システムを管理、運用", $sprite="users")
Person(userNoRepo, "機関リポジトリがない研究者", "", $sprite="users")
Person(userRPDep,"研究推進部門","外部資金等による研究を支援",$sprite="users")

System_Boundary(system_jc, "JAIRO Cloud") {
    Container(jc_repo, "機関リポジトリ", "WEKO3", "機関の研究成果を\n収集・公開")
    ' ContainerDb(jc_db, "データベース", "PostgreSQL", "研究成果のメタデータ、\n識別子情報、著者情報、\n利用統計情報等を格納", $sprite="postgresql")
    ' ContainerDb(jc_db_es, "データベース", "elasticsearch", "検索用メタデータ、\n本文テキスト\n利用統計情報を格納", $sprite="elasticsearch")
    ' ContainerQueue(jc_queue, "メッセージキュー", "RabbitMQ", "非同期処理", $sprite="rabbitmq")
    Container(ums,"UMS","","JAIRO Cloudのユーザを管理")
    Component(loginproxy,"LoginProxy","","GakuNin IdP経由でのログインをプロキシ")
    Container(oa_assist,"OAアシスト","","機関のOA論文登録を支援")
    Container(oa_dashboard,"OAダッシュボード","","機関のOA状況を管理")
    Component(restricted_access,"制限公開機能","","研究データを制限公開")
    Container(dashboard_4r,"研究者用ダッシュボード","","研究者による研究成果の管理を支援",$tags="constructing")
    ContainerDb(oa_policy,"OAポリシーDB","","雑誌のOAポリシを収集、格納")
    ContainerDb(oa_db,"OA論文DB","","OA論文メタデータ及び関連情報を収集、格納")

    System_Boundary(system_shared_repo, "共用リポジトリ") {
        Container(shared_repo,"共用リポジトリ","WEKO3","機関リポジトリを持たない研究者の研究成果を収集、公開",$tags="constructing")
    }

}


System_Boundary(system_grdm, "GakuNin RDM") {
    Container(grdm,"GakuNin RDM","GakuNin RDM","機関に所属する研究者の\n研究成果を管理、保存",$link="https://rdm.nii.ac.jp")
    Component(dg,"Data Governance","Data Governance","機関に所属する研究者のデータガバナンス機能を提供")
}

System_Boundary(system_univ, "機関システム") {
    Container(GakuNinIdP,"GakuNin IdP","Shibboleth IdP","")
    ContainerDb(univStorage,"機関ストレージ","","")
}

ContainerDb_Ext(lens,"Lens.org","","")
ContainerDb_Ext(openalex,"OpenAlex","","")
ContainerDb_Ext(unpaywall,"Unpaywall","","")
ContainerDb_Ext(erad,"eRad","","")
ContainerDb_Ext(sherparomeo,"Sherpa/Romeo","","")
ContainerDb_Ext(scpj,"SCPJ","","")
ContainerDb_Ext(jstage,"JSTAGE","","")
ContainerDb_Ext(rmap,"ResearchMap","","")
ContainerDb_Ext(crossref,"CrossRef","","")
ContainerDb_Ext(datacite,"DataCite","","")
ContainerDb_Ext(jalc,"JaLC","","")


Container(irdb,"IRDB","IRDB","機関リポジトリのメタデータを収集")
Container(cir,"CiNii","CiNii","日本の研究成果を検索")    
Container(cidashboard,"CiNiiダッシュボード","CiNiiダッシュボード","機関の学術情報流通状況を可視化？")
Container(osmon,"OSモニタ","OSモニタ","日本のOS状況を可視化")

Container(curation,"Curation","Curation","")

Rel(curation,jc_repo,"メタデータキュレーション？")
Rel(curation,grdm,"メタデータキュレーション？")


Rel(irdb,jc_repo,"メタデータの収集","OAI-PMH")
Rel(cir,irdb,"メタデータの収集","OAI-PMH")
Rel(cidashboard,cir,"Knowledge Graphを収集")


Rel(oa_assist,jc_repo,"OA論文メタデータの登録","SWORDv3")
Rel(oa_assist,oa_policy,"OAポリシを検索")
Rel(oa_policy,sherparomeo,"OAポリシを収集")
Rel(oa_policy,scpj,"OAポリシを収集",$tags="dashed")
Rel(oa_assist,oa_db,"OAポリシを検索")
Rel(oa_db,lens,"英語論文情報を収集")
Rel(oa_db,jstage,"日本語論文情報を収集")
Rel(restricted_access,jc_repo,"制限公開機能を提供","")

Rel(jc_repo,oa_dashboard,"OAステータスの更新","https")
Rel(jc_repo,ums,"ユーザ認証","shibboleth")
Rel(jc_repo,rmap,"研究者の業績情報を登録","https",$tags="dotted")

Rel(GakuNinIdP,loginproxy,"ユーザ認証","Shibboleth")
Rel(loginproxy,ums,"ユーザ認証","https")


Rel(grdm,jc_repo,"研究成果の登録","SWORDv3")
Rel(dg,grdm,"連携","https")

Rel(dashboard_4r,jc_repo,"研究成果情報の取得","https")
Rel(dashboard_4r,oa_dashboard,"OAステータスの取得","https")
Rel(dashboard_4r,shared_repo,"研究成果情報の取得","https")


Rel(userLib, jc_repo, "機関リポジトリの運用管理", "https")
Rel(userLib, oa_assist, "機関のOA論文の確認、登録", "https")
Rel(userLib, oa_dashboard, "機関のOA論文の状況を管理", "https")
Rel(userLib,ums,"ユーザアカウントの管理","https")

Rel(userRes, jc_repo, "研究成果の登録、利用", "https")
Rel(userRes, grdm, "研究データの登録、管理", "https")
Rel(userRes, dashboard_4r,"OA実施状況の確認", "https")
Rel(userRes, GakuNinIdP,"認証","https")
Rel(userRes, ums,"認証","https")

Rel(userNoRepo, shared_repo, "研究成果の登録、利用", "https")

Rel(userIT, GakuNinIdP, "機関のユーザアカウントを管理", "https")
Rel(userIT, univStorage, "機関のストレージを管理", "https")

Rel(userRPDep, osmon,"機関のOS状況を確認","https")
Rel(userRPDep, oa_dashboard,"機関のOA状況を確認","https")

@enduml