@startuml

header Architecture
footer 1 of 1
title IRDBアーキテクチャ図

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/General/Users.puml
!include AWSPuml/AWSSimplified.puml

archimate #Application "JAIRO Cloud" as JC
archimate #Application "CiNii" as CIR
note bottom of CIR: ・CiNii Research\n・CiNii Dissertations
archimate #Application "IRDB" as IRDB
archimate #Application "ジャパンリンクセンター(JaLC)" as JALC
note bottom of JALC: DOIの付与
archimate #Application "国立国会図書館(NDL)" as NDL
note bottom of NDL: ・博士論文本文の自動提出\n・国立国会図書館サーチ
archimate #Application "医学中央雑誌刊行会" as ICHUSHI
note bottom of ICHUSHI: ・医中誌Web\n最新看護索引Web
archimate #Application "OpenAIRE" as OPENAIRE
archimate #Application "他の機関リポジトリ" as OTHER_IR

IRDB -up-> CIR: OAI-PMH<<JPCOARスキーマ>>
IRDB <-down- JC: OAI-PMH<<JPCOARスキーマ>>
IRDB <-down- OTHER_IR: OAI-PMH<<JPCOARスキーマ>>
IRDB -up-> NDL: OAI-PMH
IRDB -up-> JALC: OAI-PMH
IRDB -up-> ICHUSHI: OAI-PMH?
IRDB -up-> OPENAIRE: OAI-PMH<<oai_dc?>>

rectangle "$UsersIMG()\nユーザ1" as USER

USER -up-> IRDB: "・コンテンツの検索\n・統計情報の利用"

@enduml