@startuml

header Architecture
footer 1 of 1
title W-OA-03

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/refs/heads/main/icons/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/postgresql.puml
!include DEVICONS2/elasticsearch.puml

AddElementTag("new", $fontColor="#ffffbf", $borderColor="#ffffbf",$bgColor="#444444",$legendText="開発対象")
AddElementTag("dotted", $fontColor="#000000",$borderColor="#000000",,$bgColor="#ffffff",$borderStyle=DashedLine())
AddRelTag("dotted", $lineStyle = DottedLine())
AddRelTag("dashed", $lineStyle = DashedLine())
AddRelTag("new", $lineStyle=BoldLine(), $lineColor="#FF0000",$legendText="開発対象")

Person(userRes, "研究者", "", $sprite="users")
Person(userLib,"図書館員", "", $sprite="users")

System_Boundary(system_jc, "JAIRO Cloud") {
    Container(jc_repo, "機関リポジトリ", "WEKO3", "機関の研究成果を\n収集・公開",$tags="new"){
        ComponentDb(author_db,"著者DB","","著者情報を収集、格納")
    }
    
    Container(oa_assist,"OAアシスト","","機関のOA論文登録を支援")
    Container(oa_dashboard,"OAダッシュボード","","機関のOA状況を管理")
    ContainerDb(oa_policy,"OAポリシーDB","","雑誌のOAポリシを収集、格納")
    ContainerDb(oa_db,"OA論文DB","","OA論文メタデータ及び関連情報を収集、格納")
}


System_Boundary(system_grdm, "GakuNin RDM") {
    Container(grdm,"GakuNin RDM","GakuNin RDM","機関に所属する研究者の\n研究成果を管理、保存",$link="https://rdm.nii.ac.jp")
}


' meta
ContainerDb_Ext(lens,"Lens.org","OpenAlex, PubMed, Crossref,",$link="https://about.lens.org/release-8-5/")
' search issn
ContainerDb_Ext(sherparomeo,"Sherpa/Romeo","","")
' journal meta
ContainerDb_Ext(jstage,"JSTAGE","","")
ContainerDb_Ext(openapc,"OpenAPC","","")
' url
ContainerDb_Ext(policypage,"雑誌ポリシ掲載ページ","","")
' policy page
ContainerDb_Ext(scpj,"SCPJ","","")
' 機関単位
ContainerDb_Ext(rmap,"ResearchMap","","")

Rel(oa_db,lens,"","https","")
Rel(oa_db,sherparomeo,"ISSNでOAポリシ情報を検索","https","")
Rel(oa_db,jstage,"雑誌情報をクロールして取得","https","")

Rel(oa_policy,policypage,"ポリシページ情報を収集","https","")
Rel(oa_policy,scpj,"雑誌ポリシURLを取得")
Rel(oa_db,openapc,"APC情報を取得","https","")
Rel(oa_db,rmap,"機関所属の研究者の最新業績を取得","https","")

ContainerDb_Ext(erad,"eRad","","")


Rel(userRes,jc_repo,"即時OA対象のDOIを入力","https","1-1")
Rel(jc_repo,oa_assist,"API経由で論文情報を取得","https","1-2",$tags="new")
Rel(oa_assist,oa_db,"論文情報を取得","","1-3")
Rel(oa_assist,oa_policy,"OAポリシ情報を取得","","1-4")
Rel(oa_assist,jc_repo,"論文情報を提供","https","1-5")
Rel(jc_repo,userRes,"論文情報を表示","https","1-6")
Rel(userLib,jc_repo,"不足情報を入力し、登録","https","1-7")
Rel(jc_repo,erad,"プロジェクト情報を取得","https","1-8")
Rel(userLib,jc_repo,"登録内容を確認し、公開","https","1-9")

Rel(jc_repo,oa_dashboard,"OA状況を更新","https","1-10",$tags="new")

Rel(grdm,jc_repo,"DOIのみの情報で登録","https","2-1")
Rel(jc_repo,oa_assist,"API経由で論文情報を補間","https","2-2",$tags="new")
Rel(jc_repo,grdm,"登録結果を通知","https","2-3")

SHOW_LEGEND()
@enduml