@startuml

header Architecture
footer 1 of 1
title 即時OA関連システムのアーキテクチャ図

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/refs/heads/main/icons/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/postgresql.puml
!include DEVICONS2/elasticsearch.puml


AddElementTag("new", $fontColor="#ffffbf", $borderColor="#ffffbf",$bgColor="#444444")
AddElementTag("dotted", $fontColor="#000000",$borderColor="#000000",,$bgColor="#ffffff",$borderStyle=DashedLine())
AddRelTag("dotted", $lineStyle = DottedLine())
AddRelTag("dashed", $lineStyle = DashedLine())

Person(researcher,"在野研究者",$sprite="users")
Person(guest,"研究者",$sprite="users")

'Container_Ext(orthros,"Orthros")
'Container_Ext(google, "Google")
Container_Ext(orcid,"ORCID")


Container(shared_repo,"共用リポジトリ","WEKO3","機関リポジトリを持たない研究者の研究成果を収集、公開"){
    Component(reg,"登録IF")
    Component(stat,"利用統計IF",$tags="new")
}

Container(dashboard_4r,"研究者用ダッシュボード","","研究者による研究成果の管理を支援")
Container(oa_assist,"OAアシスト","","機関のOA論文登録を支援")

Container(rmap,"researchmap")

Rel(researcher,shared_repo,"アクセス","https","1")
Rel(shared_repo,orcid,"リダイレクト","https","2")
Rel(orcid,researcher,"ログイン画面の表示","https","3")
Rel(researcher,orcid,"ログイン","https","4")
Rel(orcid,shared_repo,"ログイン処理","https","5")

Rel(researcher,reg,"OA論文のDOIの入力","https","6")
Rel(reg,oa_assist,"OAアシストAPIを利用してメタデータを補完","https","7")
Rel(oa_assist,reg,"補完用メタデータの提供","https","7")
Rel(researcher,reg,"不足メタデータの入力","https","8")
Rel(reg,dashboard_4r,"登録状況の更新","https","9")
Rel(reg,rmap,"登録情報の更新","https","10")

Rel(researcher,reg,"根拠データの登録","https","11")
Rel(reg,dashboard_4r,"登録状況の更新","https","12")
Rel(reg,rmap,"登録情報の更新","https","13")

Rel(guest,shared_repo,"アクセス","https","14")

Rel(researcher,stat,"利用統計の閲覧","https","15")

Rel(dashboard_4r,stat,"利用統計情報の取得","https","16")


@enduml