@startuml

header Architecture
footer 1 of 1
title W-OA-04

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/refs/heads/main/icons/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml
!include DEVICONS/postgresql.puml
!include DEVICONS2/elasticsearch.puml

AddElementTag("new", $fontColor="#ffffbf", $borderColor="#ffffbf",$bgColor="#444444",$legendText="開発対象")
AddElementTag("dotted", $fontColor="#000000",$borderColor="#000000",,$bgColor="#ffffff",$borderStyle=DashedLine())
AddRelTag("dotted", $lineStyle = DottedLine())
AddRelTag("dashed", $lineStyle = DashedLine())
AddRelTag("new", $lineStyle=BoldLine(), $lineColor="#FF0000",$legendText="開発対象")

Person(userRes, "研究者", "", $sprite="users")
Person(userLib,"図書館員", "", $sprite="users")
Person(userZaiyaRes,"在野研究者","",$sprite="users")

System_Boundary(system_jc, "JAIRO Cloud") {
    Container(jc_repo, "機関リポジトリ", "WEKO3", "機関の研究成果を\n収集・公開")
    Container(oa_assist,"OAアシスト","","機関のOA論文登録を支援")
    Container(oa_dashboard,"OAダッシュボード","","機関のOA状況を管理")
    Container(res_dashboard,"研究者用ダッシュボード","","研究者による研究成果の管理を支援",$tags="new")
    ContainerDb(res_dashboard_cache,"キャッシュDB")
}

Rel(res_dashboard,res_dashboard_cache,"キャッシュする","https","")

Container(shared_repo, "共用リポジトリ", "WEKO3", "")

System_Boundary(system_grdm, "GakuNin RDM") {
    Container(grdm,"GakuNin RDM","GakuNin RDM","機関に所属する研究者の\n研究成果を管理、保存",$link="https://rdm.nii.ac.jp")
}

Rel(userLib,oa_assist,"1-1 論文のメタデータを登録する","https","")
Rel(oa_assist,jc_repo,"1-2 アイテムを登録する","SWORDv3","")
Rel(userLib,userRes,"1-3 本文ファイルの登録を依頼する","mail","")
Rel(userRes,oa_dashboard,"1-4 OA状況を確認する","https","")
Rel(userRes,grdm,"1-5 本文ファイル・根拠データを登録する","https","")
Rel(grdm,jc_repo,"1-2 アイテムを登録する","SWORDv3","")
Rel(jc_repo,oa_dashboard,"1-3 OA状況を更新する","https","")
Rel(userRes,res_dashboard,"1-6 OA状況を確認する","https","",$tags="new")
Rel(res_dashboard,jc_repo,"1-7 OA登録状況、利用統計情報を取得する","https","",$tags="new")

Rel(userRes,res_dashboard,"2-1 OA登録状況を確認する","https","",$tags="new")
Rel(res_dashboard,oa_dashboard,"3-2 即時OA登録候補を取得する","https","",$tags="new")
Rel(res_dashboard,jc_repo,"3-2 OA登録状況を取得する","https","",$tags="new")
Rel(userRes,jc_repo,"3-3 論文及び根拠データを登録する","https","")

Rel(userZaiyaRes,res_dashboard,"3-1 OA登録状況を確認する","https","",$tags="new")
Rel(res_dashboard,oa_dashboard,"3-2 即時OA登録候補を取得する","https","",$tags="new")
Rel(res_dashboard,shared_repo,"3-2 OA登録状況を取得する","https","",$tags="new")
Rel(userZaiyaRes,shared_repo,"3-3 論文及び根拠データを登録する","https","")

SHOW_LEGEND()
@enduml