@startuml
' http://plantuml.com/
' https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml


'title ユースケース図

left to right direction
skinparam packageStyle rectangle

actor GUEST as "ゲスト"
' 教員
actor 登録ユーザ
' 図書館員,モデレータ
actor リポジトリ管理者
actor システム管理者
' 外部システム
actor IRDB 
actor ERDB_JP
actor RSS_Reader
actor GRDM

' WEKO3
actor コミュニティ管理者

rectangle WEKO3 {

' ゲスト
usecase UC_GUEST_0010 as "アイテムをキーワード検索で探す"
usecase UC_GUEST_0020 as "アイテムを全文検索で探す"
usecase UC_GUEST_0030 as "アイテムを詳細検索で探す"
usecase UC_GUEST_0040 as "アイテムをインデックスツリー経由で探す"
usecase UC_GUEST_0050 as "アイテム詳細画面を閲覧する"
usecase UC_GUEST_0050 as "アイテム詳細画面でアイテムの利用統計を閲覧する"
usecase UC_GUEST_0050 as "アイテム詳細画面でアイテムのバージョンを閲覧する"
usecase UC_GUEST_0060 as "アイテム詳細画面からコンテンツをダウンロードする"
usecase UC_GUEST_0070 as "アイテム詳細画面でコンテンツをプレビューする"
usecase UC_GUEST_0080 as "アイテム詳細画面からコンテンツ詳細画面を開く"
usecase UC_GUEST_0090 as "アイテム詳細画面からメタデータをエクスポートする"
usecase UC_GUEST_0100 as "アイテム詳細画面からアイテムのメタデータを共有する"
usecase UC_GUEST_0110 as "アイテム詳細画面を印刷する"
usecase UC_GUEST_0120 as "表示言語を変更する"
usecase UC_GUEST_0121 as "ログイン画面を表示する"
usecase UC_GUEST_0130 as "アイテムランキングを閲覧する"
usecase UC_GUEST_0140 as "コミュニティ一覧を閲覧する"
usecase UC_GUEST_0150 as "アイテムをファセット検索で探す"


GUEST -- UC_GUEST_0010
GUEST -- UC_GUEST_0020
GUEST -- UC_GUEST_0030
GUEST -- UC_GUEST_0040
GUEST -- UC_GUEST_0050
GUEST -- UC_GUEST_0060
GUEST -- UC_GUEST_0070
GUEST -- UC_GUEST_0080
GUEST -- UC_GUEST_0090
GUEST -- UC_GUEST_0100
GUEST -- UC_GUEST_0110
GUEST -- UC_GUEST_0120
GUEST -- UC_GUEST_0121
GUEST -- UC_GUEST_0130
GUEST -- UC_GUEST_0140
GUEST -- UC_GUEST_0150


' 登録ユーザ
登録ユーザ -- (アイテムを登録する)

' リポジトリ管理者
リポジトリ管理者 -- (アイテムタイプを作成する)
リポジトリ管理者 -- (アイテムタイプを編集する)
リポジトリ管理者 -- (アイテムを一括管理する)
リポジトリ管理者 -- (インデックスツリーを編集する)
リポジトリ管理者 -- (アイテムを査読／承認する)
リポジトリ管理者 -- (インポートする)
リポジトリ管理者 -- (ログ解析結果を閲覧する)
リポジトリ管理者 -- (デザインをカスタマイズする)
リポジトリ管理者 -- (ランキングを管理する)
リポジトリ管理者 -- (OAI-PMHを管理する)

' コミュニティ管理者
コミュニティ管理者 -- (コミュニティを管理する)

' システム管理者
システム管理者  -- (ユーザを管理する)

' 外部システム連携
(OAI-PMH経由メタデータを提供する) -- IRDB
(KBART経由で雑誌情報を提供する) -- ERDB_JP
(RSS経由でアイテム情報を提供する) --  RSS_Reader

}
@enduml